package com.hyva.restopos.rest.pojo;

import lombok.Data;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class RetailDTO extends AbstractResponse implements Serializable {

    private List<SelectedItem> selectedItemsList = new ArrayList<>();
    private String operation;
    private CashPayment cashPayment;
    private List<TaxSummary> taxWiseSummaryList = new ArrayList<>();
    private CreditCardPayment creditPayment;
    private VoucherPayment voucherPayment;
    private MultiPayment multiPayment;
    private BankPayment bankPayment;
    private float hiPosServiceCharge;
    private String paymentType;
    private String tableNo;
    private double totalCheckOutamt;
    private double otherChargesAmt;
    private double totalTaxAmt;
    private double cessTotalTaxAmt;
    private int itemCount;
    private long customerId;
    private String taxType;
    private long siid;
    private String customerEmail;
    private double totalServiceCharge;
    private String siNo;
    private double billWiseDiscount;
    private String orderNo;
    private String srlnNo;
    private String orderType;
    private String cutomerName;
    private double balanceAmount;
    private double remainingAmountBalance;
    private CustomerPojo customer;
    private double discountAmount;
    private double totalTenderedAmount;
    private String userName;
    private  String printType;
    private String billToAddress;
    private String shipToAddress;
    private String mobileNo;
    private String email;
    private String phoneNumber;
    private String inventoryAddress;
    private String inventoryName;
    private String inventoryContactNo;
    private String inventoryEmail;
    private String inventoryFax;
    private String advancepayment;
    private String formNo;
    private String totalCashPymtAmtReturned;
    private String totalChequePymtAmtReturned;
    private String totalVoucherPymtAmtReturned;
    private String chequeNumber;
    private String voucherNumber;
    private String  type_doc;
    private String  type_flag;
    private String companyLogoPath;
    private String cmpyLocation;
    private String custLocation;
    private String dateOfInvoice;
    private String agentIdOfInvoice;
    private double totalCashPayment;
    private double totalVoucherPayment;
    private double totalCardPayment;
    private String customerAddress;
    private String customerState;
    private String customerGst;
    private String locationAddress;
    private String locationState;
    private String discountType;
    private String locationGst;
    private String locationContactPerson;
    private String locationGContactNo;
    private double roundingAdj;
    private double totalAmt;
    private BigDecimal ARBalance;
    private String memo;
    private String invoiceType;
    private String returnReason;
    private String totalRemaininBalance;
    private Date shippingDate;
    private String shippingReferenceNo;
    private String referenceNo;
    private double totalVoucherAmt;
    private double totalCreditCardAmt;
    private double totalCashAmt;
    private String serviceCharge;
    private String agentName;
    private String exchangerateValue;
    private String tc_value;
    private String otherContactId;
    private Date invoiceDate;
    private double invoiceAmt;
    private double incrementAmt;
    private String employeeId;
    private double tokenNo;
    private String table;
    private String mainTable;
    private String invoiceNo;
    private Date formDate;
    private Long invokeOrderId;
    private String invokeOrderName;
    private String customerPo;
    private double amtToBePaid;
    private String siStatus;
   private String employeeName;
   private String vehicleNo;
   private String distance;
   private String transporterId;
   private String customerPincode;
   public boolean roundingStatus;
   public boolean smsType;
   public String roundingOffValue;
   public String personIncharge;
   public String locationEmail;
   public String returnType;
   private float discountAmtInPercentage;
   private boolean bluetoothStatus;
   private double hiposServiceChargeAmt;
   private double restaurantDiscount;
   private double amountReturned;
   private String customerNo;
    public Map<String,String> tableName;
    private String custPaymentNo;
    private Long custPaymentId;
    private Long posPaymentId;
    private String pax;
    private String discountCode;
    private String discType;
    private AirPayPayment airPayments;
    private List<InvoicePayment> invoicePaymentList = new ArrayList<>();
    private String olInvPayId;
    private String airPayId;
    private boolean isAirPayPayment;
}
